export const PREDEFINED_SKILLS = [
  "Figma",
  "UI Design",
  "UX Design",
  "Wireframing",
  "Prototyping",
  "HTML",
  "CSS",
  "JavaScript",
  "React.js",
  "TypeScript",
  "Dart",
  "Flutter",
  "Firebase",
  "REST API",
  "Git",
  "Python",
  "Node.js",
  "Express.js",
  "SQL",
  "Pandas",
  "Power BI",
  "Statistics",
  "PyTorch",
  "TensorFlow",
  "Deep Learning",
  "NLP",
  "Kotlin",
  "Java",
  "Android Studio",
  "Android SDK",
  "C++",
  "OOP",
  "Data Structures",
  "C",
  "Arduino",
  "ESP32",
  "STM32",
  "Linux",
  "Networking",
  "Nmap",
  "Wireshark",
  "NumPy",
  "Scikit-learn",
  "Machine Learning",
  "LLM",
  "RAG",
  "Embeddings",
  "Hugging Face",
  "Selenium",
  "Postman",
  "PyTest",
  "API Testing",
  "Automation Testing",
  "ROS",
  "OpenCV",
  "C#",
  "Unity",
  "Unreal Engine",
  "Game Physics",
  "React Native",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Swift",
  "SwiftUI",
  "Xcode",
  "UIKit",
  "AutoCAD",
  "SolidWorks",
  "CATIA",
  "3D Modeling",
  "CAD",
  "Apache Spark",
  "Kafka",
  "Airflow",
  "AWS",
  "Azure",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Solidity",
  "Ethereum",
  "Web3.js",
  "Smart Contracts",
  "Jenkins",
  "CI/CD",
  "Transformers",
  "BERT",
  "YOLO",
  "CNN",
  "MQTT",
  "Verilog",
  "SystemVerilog",
  "VHDL",
  "FPGA",
  "RTL Design",
  "Bash",
  "Operating Systems",
  "B2B Sales",
  "Field Sales",
  "Lead Generation",
  "English Proficiency (Spoken)",
  "English Proficiency (Written)",
  "Google Sheets",
  "Mathematics",
  "MS-Excel",
  "Statistical Modeling",
  "Human Resources",
  "MS-Office",
  "Recruitment",
  "Resume screening",
  "Content Marketing",
  "Digital Marketing",
  "Sales",
  "Social Media Marketing",
  "Content Management",
  "Search Engine Optimization (SEO)",
  "Video Editing",
  "Video Making",
  "Effective Communication",
  "Blogging",
  "Creative Writing",
  "Written Communication",
  "Analytical Thinking",
  "Data Extraction",
  "MS-PowerPoint",
  "MS-Word",
  "Problem Solving",
  "Hindi Proficiency (Spoken)",
  "Telugu Proficiency (Spoken)",
  "Interpersonal skills",
  "Negotiations",
  "Legal Drafting",
  "Legal Research",
  "Legal Writing",
  "Statutory compliances",
  "Community Management",
  "Event Management",
  "Client Relationship Management (CRM)",
  "E-commerce",
  "Key Account Management",
  "Logistics Management",
  "Email Marketing",
  "Presentation skills",
  "Research and Analytics",
  "Content Editing",
  "Photography",
  "Business Management",
  "Business Research",
  "Market Analysis",
  "Marketing Campaigns",
  "Marketing Strategy",
  "Content Writing",
  "Public Relations",
  "Canva",
  "Generative AI Tools",
  "Attention to Detail",
  "Email Management",
  "Sales Strategy",
  "Artificial intelligence",
  "Computer skills",
] as const;